FROM maven:latest AS BUILD

WORKDIR /app
COPY . .
RUN mvn package

# geoserver/src/community/xslt does not exist in newer GeoServer versions so we checkout and build from an earlier version, 2.25.3
WORKDIR /gsbuild
RUN git clone -b 2.25.3 --depth 1 https://github.com/geoserver/geoserver.git

WORKDIR /gsbuild/geoserver/src/community/xslt
RUN mvn package

# rename the dir to keep it distinct from the "geoserver" dir we clone below
RUN mv geoserver geoserver-2.25.3

# Clone and build from a new version of GeoServer
WORKDIR /gsbuild
RUN git clone -b 2.28.2 --depth 1 https://github.com/geoserver/geoserver.git

WORKDIR /gsbuild/geoserver/src/kml
RUN mvn package

WORKDIR /gsbuild/geoserver/src/rest
RUN mvn package

WORKDIR /gsbuild/geoserver/src/restconfig
RUN mvn package

FROM geoservercloud/geoserver-cloud-wfs:2.28.2.2

COPY --from=BUILD /gsbuild/geoserver-2.25.3/src/community/xslt/target/gs-xslt-2.25.3.jar /opt/app/bin/BOOT-INF/lib/gs-wfs-bcgov-xslt-2.25.3.jar

COPY --from=BUILD /gsbuild/geoserver/src/rest/target/gs-rest-2.28.2.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=BUILD /gsbuild/geoserver/src/restconfig/target/gs-restconfig-2.28.2.jar /opt/app/bin/BOOT-INF/lib/.

# Adding support for KML
COPY --from=BUILD /gsbuild/geoserver/src/kml/target/gs-kml-2.28.2.jar /opt/app/bin/BOOT-INF/lib/.

COPY --from=BUILD /app/target/gs-wfs-bcgov-2.26.0.jar /opt/app/bin/BOOT-INF/lib/.

RUN curl -o /opt/app/bin/BOOT-INF/lib/JavaAPIforKml-2.2.1.jar \
  https://repo1.maven.org/maven2/de/micromata/jak/JavaAPIforKml/2.2.1/JavaAPIforKml-2.2.1.jar

RUN curl -O https://repo1.maven.org/maven2/p6spy/p6spy/3.9.1/p6spy-3.9.1.jar \
 && mv p6spy-3.9.1.jar /opt/app/bin/BOOT-INF/lib/p6spy-3.9.1.jar
