FROM geoservercloud/geoserver-cloud-wms:2.28.2.2 as gscloud

RUN apt-get update && apt-get install unzip
WORKDIR /tmp

RUN cp /opt/app/bin/BOOT-INF/lib/gs-main-2.28.2.2.jar gs-main.jar \
 && unzip gs-main.jar

FROM docker.io/node:25.8-bookworm

WORKDIR /app

COPY . .
RUN npm i

COPY --from=gscloud /tmp/schemas public/geo/schemas

ENTRYPOINT [ "node", "index.js" ]