FROM geoservercloud/geoserver-cloud-wms:1.9-RC as gscloud

RUN apt-get update && apt-get install unzip
WORKDIR /tmp

RUN cp /opt/app/bin/BOOT-INF/lib/gs-main-2.26.0-SNAPSHOT.jar gs-main.jar \
 && unzip gs-main.jar

FROM docker.io/node:22.6-bookworm

WORKDIR /app

COPY . .
RUN npm i

COPY --from=gscloud /tmp/schemas public/schemas
RUN chmod -R 0444 public

ENTRYPOINT [ "node", "index.js" ]