FROM geoservercloud/geoserver-cloud-wms:1.9-SNAPSHOT AS wms

FROM maven:latest AS BUILD

WORKDIR /app
COPY . .
RUN mvn package

WORKDIR /gsbuild
RUN git clone -b 2.25.3 --depth 1 https://github.com/geoserver/geoserver.git

WORKDIR /gsbuild/geoserver/src/community/xslt
RUN mvn package

WORKDIR /gsbuild/geoserver/src/kml
RUN mvn package

WORKDIR /gsbuild/geoserver/src/rest
RUN mvn package

WORKDIR /gsbuild/geoserver/src/restconfig
RUN mvn package

FROM geoservercloud/geoserver-cloud-wfs:1.9-SNAPSHOT

# COPY --from=BUILD /gsbuild/geoserver/src/rest/target/gs-rest-2.25.3.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=BUILD /gsbuild/geoserver/src/restconfig/target/gs-restconfig-2.25.3.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=BUILD /gsbuild/geoserver/src/community/xslt/target/gs-xslt-2.25.3.jar /opt/app/bin/BOOT-INF/lib/gs-wfs-bcgov-xslt-2.25.3.jar

# Adding support for KML
#COPY --from=BUILD /gsbuild/geoserver/src/kml/target/gs-kml-2.25.3.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=BUILD /app/target/gs-wfs-bcgov-2.26.0.jar /opt/app/bin/BOOT-INF/lib/.

COPY --from=wms /opt/app/bin/BOOT-INF/lib/asm-analysis-9.2.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/asm-tree-9.2.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/asm-util-9.2.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/encoder-1.2.3.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gs-cloud-starter-wms-extensions-1.9-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gs-css-2.26.0-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gs-kml-2.26.0-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gs-mbstyle-2.26.0-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gs-rest-2.26.0-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gs-vectortiles-2.26.0-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gt-css-32-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gt-geojson-core-32-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gt-mbstyle-32-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/gt-svg-32-SNAPSHOT.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/imageio-ext-png-1.4.12.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/ion-java-1.0.2.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/jackson-dataformat-cbor-2.17.2.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/JavaAPIforKml-2.2.0.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/java-vector-tile-1.3.9.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/jmespath-java-1.12.261.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/json-simple-1.1.1.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/parboiled-core-1.4.1.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/parboiled-java-1.4.1.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/pngj-2.0.1.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/xml-apis-ext-1.3.04.jar /opt/app/bin/BOOT-INF/lib/.
COPY --from=wms /opt/app/bin/BOOT-INF/lib/xmlgraphics-commons-2.9.jar /opt/app/bin/BOOT-INF/lib/.
