FROM geoservercloud/geoserver-cloud-wms:1.9-SNAPSHOT

RUN apt update && apt install -y fonts-liberation
# ttf-mscorefonts-installer <-- requires a license to be accepted :(

# $ fc-match Arial
# LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
