locustfile = locustfile-replay-log-more-users.py
headless = false
host = https://test.openmaps.gov.bc.ca

users = 1
# spawn-rate is users / second
spawn-rate = 3
#run-time = 35m
csv = _tmp/results.csv
html = _tmp/results.html