apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: admin
  name: admin
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 8080
  selector:
    io.kompose.service: admin
