apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: admin
  name: admin
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: geoservercloud/geoserver-cloud-admin-server:1.5.0
      name: 1.5.0
      referencePolicy:
        type: ""
