apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    io.kompose.service: gateway
  template:
    metadata:
      labels:
        io.kompose.network/geoserver-cloud-gs-cloud-network: "true"
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: datadir
          image: ' '
          name: gateway
          ports:
            - containerPort: 8080
              # hostPort: 9090
              protocol: TCP
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - gateway
        from:
          kind: ImageStreamTag
          name: gateway:1.5.0
      type: ImageChange
