apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: shared-data-directory
  name: shared-data-directory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
