kind: Deployment
apiVersion: apps/v1
metadata:
  name: oracle-toolbox
  labels:
    app: oracle-toolbox
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oracle-toolbox
  template:
    metadata:
      labels:
        app: oracle-toolbox
    spec:
      volumes:
        - name: oracle-jndi-secret-vol
          secret:
            secretName: oracle-jndi
      containers:
        - name: busybox
          image: >-
            docker.io/busybox
          command: [sh]
          args:
            - -c
            - |
              sleep infinity

          resources:
            limits:
              cpu: 90m
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 100Mi

        - name: sqlplus
          image: ghcr.io/oracle/oraclelinux8-instantclient:21
          command: [sh]
          args:
            - -c
            - |
              sleep infinity
          ports: []
          env:
            - name: ORACLE_URL
              valueFrom:
                secretKeyRef:
                  name: oracle-jndi
                  key: url
            - name: ORACLE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-jndi
                  key: username
            - name: ORACLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-jndi
                  key: password
            - name: ORACLE_LOGIN
              value: "$ORACLE_USERNAME/$ORACLE_PASSWORD@$ORACLE_URL"
              # LOGIN=`eval echo $ORACLE_LOGIN` && sqlplus $LOGIN
          resources:
            limits:
              cpu: 90m
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 100Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: oracle-jndi
type: kubernetes.io/basic-auth
stringData:
  url: ""
  username: ""
  password: ""
