kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-to-geoserver-gateway
spec:
  host: geoserver-ec38a0.apps.gold.devops.gov.bc.ca
  to:
    kind: Service
    name: gateway
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route-to-admin
spec:
  host: admin-ec38a0.apps.gold.devops.gov.bc.ca
  to:
    kind: Service
    name: admin
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
