kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
        - name: shared-data-directory
          emptyDir: {}
      containers:
        - name: test-container
          image: >-
            geoservercloud/geoserver-cloud-wms:1.5.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir,dev"
            - name: GEOSERVER_DATA_DIR
              value: /opt/app/data_directory
            # - name: RABBITMQ_PORT
            #   value: "5672"
            # - name: RABBITMQ_HOST
            #   value: rabbitmq
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data-directory
              mountPath: /opt/app/data_directory
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 20m
              memory: 100Mi
