kind: Deployment
apiVersion: apps/v1
metadata:
  name: wfs
  labels:
    app: wfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wfs
  template:
    metadata:
      labels:
        app: wfs
    spec:
      volumes:
        - name: shared-data-directory
          emptyDir: {}
      containers:
        - name: wfs-container
          image: >-
            geoservercloud/geoserver-cloud-wfs:1.9-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir"
            - name: GEOSERVER_DATA_DIR
              value: /opt/app/data_directory
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_HOST
              value: rabbitmq
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data-directory
              mountPath: /opt/app/data_directory
          resources:
            limits:
              cpu: 200m
              memory: 700Mi
            requests:
              cpu: 20m
              memory: 500Mi
