kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"geoserver-cloud-rest:1.5.0"},"fieldPath":"spec.template.spec.containers[?(@.name==\"geoserver-cloud-rest\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '2615589109'
  name: geoserver-cloud-rest
  uid: bc078212-33b4-4a4e-8c43-0b32400cfa83
  creationTimestamp: '2024-02-05T17:02:38Z'
  generation: 3
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-05T17:02:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"geoserver-cloud-rest"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8081,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/data/geowebcache"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/opt/app/data_directory"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"geoserver-cloud-rest-volume-1"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
                'k:{"name":"geoserver-cloud-rest-volume-2"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-05T17:02:39Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"geoserver-cloud-rest"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-05T17:03:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
      subresource: status
  namespace: ec38a0-dev
  labels:
    app: geoserver-cloud-rest
    app.kubernetes.io/component: geoserver-cloud-rest
    app.kubernetes.io/instance: geoserver-cloud-rest
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: geoserver-cloud-rest
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: geoserver-cloud-rest
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: geoserver-cloud-rest-volume-1
          emptyDir: {}
        - name: geoserver-cloud-rest-volume-2
          emptyDir: {}
      containers:
        - name: geoserver-cloud-rest
          image: >-
            geoservercloud/geoserver-cloud-rest@sha256:80346fe5b4fdb4154629b4f383697a77222d52a06f8c67a50f11048ead4fd317
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: geoserver-cloud-rest-volume-1
              mountPath: /data/geowebcache
            - name: geoserver-cloud-rest-volume-2
              mountPath: /opt/app/data_directory
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-02-05T17:02:47Z'
      lastTransitionTime: '2024-02-05T17:02:47Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-02-05T17:02:47Z'
      lastTransitionTime: '2024-02-05T17:02:38Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "geoserver-cloud-rest-65c45cdd9c" has successfully
        progressed.
