kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/instance: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: rabbitmq
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: rabbitmq-volume-1
          emptyDir: {}
      containers:
        - name: rabbitmq
          image: >-
            rabbitmq@sha256:cd2611ff526357b0763ae2937bee1a85b438274b55f2f2767041ca1f29f81c11
          ports:
            - containerPort: 4369
              protocol: TCP
            - containerPort: 5671
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15671
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
            - containerPort: 15691
              protocol: TCP
            - containerPort: 15692
              protocol: TCP
            - containerPort: 25672
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: rabbitmq-volume-1
              mountPath: /var/lib/rabbitmq
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
