kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"geoserver-cloud-wms:1.5.0"},"fieldPath":"spec.template.spec.containers[?(@.name==\"geoserver-cloud-wms\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '2615578670'
  name: geoserver-cloud-wms
  uid: 4955c553-4f5a-44d9-acae-dccb21164ef3
  creationTimestamp: '2024-02-05T16:53:01Z'
  generation: 2
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-05T16:53:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"geoserver-cloud-wms"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":8081,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/data/geowebcache"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/opt/app/data_directory"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"geoserver-cloud-wms-volume-1"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
                'k:{"name":"geoserver-cloud-wms-volume-2"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-05T16:53:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"geoserver-cloud-wms"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2024-02-05T16:59:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: ec38a0-dev
  labels:
    app: geoserver-cloud-wms
    app.kubernetes.io/component: geoserver-cloud-wms
    app.kubernetes.io/instance: geoserver-cloud-wms
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: geoserver-cloud-wms
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: geoserver-cloud-wms
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: geoserver-cloud-wms-volume-1
          emptyDir: {}
        - name: geoserver-cloud-wms-volume-2
          emptyDir: {}
      containers:
        - name: geoserver-cloud-wms
          image: >-
            geoservercloud/geoserver-cloud-wms@sha256:289b4f7ef3a8ada9e24c625caac4ae8b51f0e09a0e5564c122454c843cb40358
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: geoserver-cloud-wms-volume-1
              mountPath: /data/geowebcache
            - name: geoserver-cloud-wms-volume-2
              mountPath: /opt/app/data_directory
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-02-05T16:53:09Z'
      lastTransitionTime: '2024-02-05T16:53:01Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "geoserver-cloud-wms-66d9dc867" has successfully progressed.
    - type: Available
      status: 'False'
      lastUpdateTime: '2024-02-05T16:59:07Z'
      lastTransitionTime: '2024-02-05T16:59:07Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
