kind: Deployment
apiVersion: apps/v1
metadata:
  name: geoserver-cloud-gateway
  labels:
    app: geoserver-cloud-gateway
    app.kubernetes.io/component: geoserver-cloud-gateway
    app.kubernetes.io/instance: geoserver-cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: geoserver-cloud-gateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: geoserver-cloud-gateway
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: geoserver-cloud-gateway
          image: >-
            geoservercloud/geoserver-cloud-gateway@sha256:0ef3e5b60001b4fbcb895e0068e69365d2f06795b47f6c11dcbe09fefc6d0e65
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600