kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: '2024-02-05T17:04:56Z'
  resourceVersion: '2615593847'
  name: geoserver-cloud-webui
  uid: 8167f5d6-7e2c-464c-ab12-b21f9f8c58a4
  creationTimestamp: '2024-02-05T17:04:56Z'
  generation: 2
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: image.openshift.io/v1
      time: '2024-02-05T17:04:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:tags':
            .: {}
            'k:{"name":"1.5.0"}':
              .: {}
              'f:annotations':
                .: {}
                'f:openshift.io/imported-from': {}
              'f:from': {}
              'f:generation': {}
              'f:importPolicy':
                .: {}
                'f:importMode': {}
              'f:name': {}
              'f:referencePolicy':
                .: {}
                'f:type': {}
  namespace: ec38a0-dev
  labels:
    app: geoserver-cloud-webui
    app.kubernetes.io/component: geoserver-cloud-webui
    app.kubernetes.io/instance: geoserver-cloud-webui
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 1.5.0
      annotations:
        openshift.io/imported-from: 'geoservercloud/geoserver-cloud-webui:1.5.0'
      from:
        kind: DockerImage
        name: 'geoservercloud/geoserver-cloud-webui:1.5.0'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/ec38a0-dev/geoserver-cloud-webui
  publicDockerImageRepository: image-registry.apps.gold.devops.gov.bc.ca/ec38a0-dev/geoserver-cloud-webui
  tags:
    - tag: 1.5.0
      items:
        - created: '2024-02-05T17:04:56Z'
          dockerImageReference: >-
            geoservercloud/geoserver-cloud-webui@sha256:6f1d8aa91cf993aa91b8fbb381b05a4d6e376a160a39d5bb1f2b499fc07ec6a9
          image: >-
            sha256:6f1d8aa91cf993aa91b8fbb381b05a4d6e376a160a39d5bb1f2b499fc07ec6a9
          generation: 2
