kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/instance: rabbitmq
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 3.9-management
      annotations:
        openshift.io/imported-from: 'rabbitmq:3.9-management'
      from:
        kind: DockerImage
        name: 'rabbitmq:3.9-management'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
