kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: ec38a0-dev
  uid: 31a9cb91-2bc9-4e9a-87be-064af5f5bc84
  resourceVersion: '2615528438'
  creationTimestamp: '2024-02-05T16:38:38Z'
  labels:
    app: rabbitmq
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/instance: rabbitmq
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2024-02-05T16:38:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            'k:{"port":5671,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":5672,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            .: {}
            'k:{"port":4369,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":15691,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":15692,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":15671,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":15672,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
            'k:{"port":25672,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  clusterIP: 10.98.14.183
  ipFamilies:
    - IPv4
  ports:
    - name: 4369-tcp
      protocol: TCP
      port: 4369
      targetPort: 4369
    - name: 5671-tcp
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: 5672-tcp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: 15671-tcp
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: 15672-tcp
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: 15691-tcp
      protocol: TCP
      port: 15691
      targetPort: 15691
    - name: 15692-tcp
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: 25672-tcp
      protocol: TCP
      port: 25672
      targetPort: 25672
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.98.14.183
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: rabbitmq
status:
  loadBalancer: {}
