kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/instance: rabbitmq
spec:
  clusterIP: 10.98.14.183
  ipFamilies:
    - IPv4
  ports:
    - name: 4369-tcp
      protocol: TCP
      port: 4369
      targetPort: 4369
    - name: 5671-tcp
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: 5672-tcp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: 15671-tcp
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: 15672-tcp
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: 15691-tcp
      protocol: TCP
      port: 15691
      targetPort: 15691
    - name: 15692-tcp
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: 25672-tcp
      protocol: TCP
      port: 25672
      targetPort: 25672
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.98.14.183
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: rabbitmq
