kind: Service
apiVersion: v1
metadata:
  name: geoserver-cloud-wms
  labels:
    app: geoserver-cloud-wms
    app.kubernetes.io/component: geoserver-cloud-wms
    app.kubernetes.io/instance: geoserver-cloud-wms
spec:
  clusterIP: 10.98.161.115
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 10.98.161.115
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: geoserver-cloud-wms
