kind: Service
apiVersion: v1
metadata:
  name: geoserver-cloud-config
  labels:
    app: geoserver-cloud-config
    app.kubernetes.io/component: geoserver-cloud-config
    app.kubernetes.io/instance: geoserver-cloud-config
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: geoserver-cloud-config
