kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin-container
          image: >-
            geoservercloud/geoserver-cloud-admin-server:1.5.0
          ports:
            - containerPort: 8080
