kind: Deployment
apiVersion: apps/v1
metadata:
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config-container
          image: >-
            geoservercloud/geoserver-cloud-config:1.5.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: git
            - name: CONFIG_GIT_URI
              value: https://github.com/geoserver/geoserver-cloud-config.git
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: v1.5.0
            - name: CONFIG_GIT_BASEDIR
              value: /tmp/git_config
            - name: CONFIG_NATIVE_PATH
              value: /tmp/config
            - name: XDG_CONFIG_HOME
              value: /tmp
          ports:
            - containerPort: 8080
