kind: Deployment
apiVersion: apps/v1
metadata:
  name: rest
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      volumes:
        - name: shared-data-directory
          persistentVolumeClaim:
            claimName: shared-data-directory
      containers:
        - name: rest-container
          image: >-
            geoservercloud/geoserver-cloud-rest:1.5.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir"
            - name: GEOSERVER_DATA_DIR
              value: /opt/app/data_directory
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data-directory
              mountPath: /opt/app/data_directory
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 20m
              memory: 300Mi
