kind: Deployment
apiVersion: apps/v1
metadata:
  name: wfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wfs
  template:
    metadata:
      labels:
        app: wfs
    spec:
      volumes:
        - name: shared-data-directory
          persistentVolumeClaim:
            claimName: shared-data-directory
      containers:
        - name: wfs-container
          image: >-
            geoservercloud/geoserver-cloud-wfs:1.5.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "datadir"
            - name: GEOSERVER_DATA_DIR
              value: /opt/app/data_directory
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data-directory
              mountPath: /opt/app/data_directory
