name: GeoServer Image Builds

on:
  push:
    branches: [never/*]

env:
  REGISTRY: artifacts.developer.gov.bc.ca

jobs:
  # build-webui:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: "./.github/templates/build"
  #       with:
  #         image_name: webui
  #         registry: ${{ env.REGISTRY }}
  #         registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
  #         registry_username: ${{ secrets.REGISTRY_USERNAME }}
  #         registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  # build-wfs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: "./.github/templates/build"
  #       with:
  #         image_name: wfs
  #         registry: ${{ env.REGISTRY }}
  #         registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
  #         registry_username: ${{ secrets.REGISTRY_USERNAME }}
  #         registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  build-wms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/templates/build"
        with:
          image_name: wms
          registry: ${{ env.REGISTRY }}
          registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  # build-wms-p6spy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: "./.github/templates/build"
  #       with:
  #         image_name: wms-p6spy
  #         registry: ${{ env.REGISTRY }}
  #         registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
  #         registry_username: ${{ secrets.REGISTRY_USERNAME }}
  #         registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  # build-gwc:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: "./.github/templates/build"
  #       with:
  #         image_name: gwc
  #         registry: ${{ env.REGISTRY }}
  #         registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
  #         registry_username: ${{ secrets.REGISTRY_USERNAME }}
  #         registry_password: ${{ secrets.REGISTRY_PASSWORD }}
