name: GeoServer Image Builds

on:
  push:
    branches: [main, images/*]

env:
  REGISTRY: artifacts.developer.gov.bc.ca

jobs:
  build-webui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: webui
        uses: "./.github/templates/build"
        with:
          registry: ${{ env.REGISTRY }}
          registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          image_name: webui
