name: Main

on:
    push:
      branches: [images/*]
  
env:
    REGISTRY: artifacts.developer.gov.bc.ca
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}        
      - name: Release
        uses: softprops/action-gh-release@v2
      - uses: "./.github/templates/build"
        with:
            image_name: wms
            registry: ${{ env.REGISTRY }}
            registry_repo_name: ${{ secrets.REGISTRY_REPO_NAME }}
            registry_username: ${{ secrets.REGISTRY_USERNAME }}
            registry_password: ${{ secrets.REGISTRY_PASSWORD }}
